name = "bluetalk"
main = "worker.js"
compatibility_date = "2026-09-01"
workers_dev = true

kv_namespaces = [
  { binding = "BLUETALK_KV", id = "00000000000000000000000000000000" }
]

[observability]
enabled = true
